// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskBoard.Infrastructure;

#nullable disable

namespace TaskBoard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskBoard.Domain.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("action_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("action_time");

                    b.Property<int?>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("TaskBoard.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<int>("ListCardsId")
                        .HasColumnType("integer")
                        .HasColumnName("list_cards_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("ListCardsId");

                    b.ToTable("cards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Necessary QA job for the website",
                            DueDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListCardsId = 1,
                            Name = "Do QA",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The slider is displaying images with numbers 3,6,8 inappropriately",
                            DueDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListCardsId = 2,
                            Name = "Fix the bug with the slider on the main page",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The font must be Arial and the main color must be purple",
                            DueDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListCardsId = 3,
                            Name = "Change the design of the navbar",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The font must be Arial and the main color must be purple",
                            DueDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListCardsId = 2,
                            Name = "Change the design of the sidebar",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The description of products on the page 9 can't be changed",
                            DueDate = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListCardsId = 1,
                            Name = "Fix the bug with the description of products",
                            Priority = "High"
                        });
                });

            modelBuilder.Entity("TaskBoard.Domain.Entities.ListCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("list_cards_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("list_cards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            Name = "To Do"
                        },
                        new
                        {
                            Id = 3,
                            Name = "In Progress"
                        });
                });

            modelBuilder.Entity("TaskBoard.Domain.Entities.Action", b =>
                {
                    b.HasOne("TaskBoard.Domain.Entities.Card", "Card")
                        .WithMany("Actions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TaskBoard.Domain.Entities.Card", b =>
                {
                    b.HasOne("TaskBoard.Domain.Entities.ListCards", "ListCards")
                        .WithMany("Cards")
                        .HasForeignKey("ListCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListCards");
                });

            modelBuilder.Entity("TaskBoard.Domain.Entities.Card", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("TaskBoard.Domain.Entities.ListCards", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
