# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  taskboardapi:
    image: taskboardapi
    build:
      context: .
      dockerfile: TaskBoard.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7266:7266
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
