# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'
networks:
  task-board-dev:
    driver: bridge

services:
  taskboardapi:
    image: taskboardapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7266:7266
    networks:
      - task-board-dev
    depends_on:
      - localhost

  localhost:
    image: postgres:latest
    container_name: task_board_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cards_db
    ports:
      - "5433:5433"
    networks:
      - task-board-dev
    volumes:
      - postgres-data: ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: